// List of project IDs from the sample data with more detailed information
export const PROJECTS_INFO = [
    {
        id: '1000107',
        fund: 'Fund 10',
        name: 'MeshJS SDK Operations: Supporting Open-Source Library Development, Developer Resources & Builder Community',
        category: 'F10: OSDE: Open Source Dev Ecosystem',
        url: 'https://projectcatalyst.io/funds/10/f10-osde-open-source-dev-ecosystem/meshjs-sdk-operations-supporting-open-source-library-development-developer-resources-and-builder-community',
        status: 'In Progress',
        budget: 169413,
        funds_distributed: 140000,
        milestones_qty: 5,
        milestonesCompleted: 5,
        finished: 'September, 2024'
    },
    {
        id: '1100271',
        fund: 'Fund 11',
        name: 'Sustain & Maintain MeshJS',
        category: 'F11: Cardano Open: Developers',
        url: 'https://projectcatalyst.io/funds/11/cardano-open-developers/sustain-and-maintain-meshjs',
        status: 'Completed',
        budget: 150000,
        funds_distributed: 150000,
        milestones_qty: 5,
        milestonesCompleted: 5,
        finished: 'September 15, 2024'
    },
    {
        id: '1200148',
        fund: 'Fund 12',
        name: 'Mesh Software as a Service',
        category: 'F12: Cardano Use Cases: Concept',
        url: 'https://projectcatalyst.io/funds/12/f12-cardano-use-cases-concept/mesh-software-as-a-service',
        status: 'In Progress',
        budget: 100000,
        funds_distributed: 40000,
        milestones_qty: 5,
        milestonesCompleted: 2
    },
    {
        id: '1200220',
        fund: 'Fund 12',
        name: 'Sustain and Maintain Mesh SDK',
        category: 'F12: Cardano Open: Developers',
        url: 'https://projectcatalyst.io/funds/12/f12-cardano-open-developers/sustain-and-maintain-mesh-sdk',
        status: 'Completed',
        budget: 200000,
        funds_distributed: 200000,
        milestones_qty: 5,
        milestonesCompleted: 5
    },
    {
        id: '1200147',
        fund: 'Fund 12',
        name: 'Mesh New Features to Improve Developer experience and Cardano Adoption',
        category: 'F12: Cardano Open: Developers',
        url: 'https://projectcatalyst.io/funds/12/f12-cardano-open-developers/mesh-new-features-to-improve-developer-experience-and-cardano-adoption',
        status: 'In Progress',
        budget: 200000,
        funds_distributed: 160000,
        milestones_qty: 5,
        milestonesCompleted: 4
    },
    {
        id: '1300036',
        fund: 'Fund 13',
        name: 'Cardano Builder Fest Asia by Mesh, Socious, SIDAN, Vietnam Cardano',
        category: 'F13: Cardano Open: Ecosystem',
        url: 'https://projectcatalyst.io/funds/10/f13-cardano-open-ecosystem/cardano-builder-fest-asia-by-mesh-socious-sidan-vietnam-cardano',
        status: 'In Progress',
        budget: 99016,
        funds_distributed: 50000,
        milestones_qty: 4,
        milestonesCompleted: 2
    },
    {
        id: '1300134',
        fund: 'Fund 13',
        name: 'Mesh: Cquisitor - Transaction Investigation Tool',
        category: 'F13: Cardano Open: Developers',
        url: 'https://projectcatalyst.io/funds/10/f13-cardano-open-developers/mesh-cquisitor-transaction-investigation-tool',
        status: 'In Progress',
        budget: 200000,
        funds_distributed: 0,
        milestones_qty: 5,
        milestonesCompleted: 0
    },
    {
        id: '1300135',
        fund: 'Fund 13',
        name: 'Mesh: Hydra Tools for administrating & interacting with Hydra Heads',
        category: 'F13: Cardano Open: Developers',
        url: 'https://projectcatalyst.io/funds/10/f13-cardano-open-developers/mesh-hydra-tools-for-administrating-and-interacting-with-hydra-heads',
        status: 'In Progress',
        budget: 200000,
        funds_distributed: 80000,
        milestones_qty: 5,
        milestonesCompleted: 2
    },
    {
        id: '1300050',
        fund: 'Fund 13',
        name: 'Cardano Multisig Platform by Mesh, Clarity DAO & Fluid Tokens',
        category: 'F13: Cardano Use Cases: Product',
        url: 'https://projectcatalyst.io/funds/10/f13-cardano-use-cases-product/cardano-multisig-platform-by-mesh-clarity-dao-and-fluid-tokens',
        status: 'In Progress',
        budget: 500000,
        funds_distributed: 100000,
        milestones_qty: 5,
        milestonesCompleted: 1
    },
    {
        id: '1300130',
        fund: 'Fund 13',
        name: 'Maintain Mesh and Build Developer Community',
        category: 'F13: Cardano Open: Developers',
        url: 'https://projectcatalyst.io/funds/10/f13-cardano-open-developers/maintain-mesh-and-build-developer-community',
        status: 'In Progress',
        budget: 200000,
        funds_distributed: 40000,
        milestones_qty: 5,
        milestonesCompleted: 1
    }
]; 