# docs/_config.yml
title: Catalyst Tracker Documentation
description: Catalyst Tracker App Documentation and Guides
theme: just-the-docs

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Set the base URL to match your GitHub Pages URL
baseurl: "/catalyst-tracker"  # Replace with your repository name
url: "https://treasuryguild.github.io"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/treasuryguild/catalyst-tracker"

# Color scheme
color_scheme: dark

# Enable collect for search functionality
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10