name: Update MeshJS Proposal README

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at Midnight UTC every Monday
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write
  # More explicit permissions:
  issues: read
  pull-requests: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL2: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL2 }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY2: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY2 }}
      NEXT_PUBLIC_MILESTONES_URL: 'https://milestones.projectcatalyst.io'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      README_PROJECT_IDS: ${{ secrets.README_PROJECT_IDS }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update README
        run: npm run update-readme
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update MeshJS Catalyst Projects README" && git push) 