name: Update MeshJS Proposal README

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at Midnight UTC every Monday
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL2: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL2 }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY2: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY2 }}
      NEXT_PUBLIC_MILESTONES_URL: 'https://milestones.projectcatalyst.io'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      README_PROJECT_IDS: ${{ secrets.README_PROJECT_IDS }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update README
        run: npm run update-readme 